export const DEFAULT_CONFIG = {
  // Global
  LISTENING_WINDOW_MS: 1500,
  MOVE_INTERVAL_MS: 1000,
  
  // Shadow Boxing (Arm)
  JAB_ACCEL_THRESHOLD: 12,
  HOOK_GYRO_THRESHOLD: 100,
  SLIP_ACCEL_THRESHOLD: 8,
  
  // Kickboxing (Pocket)
  FRONT_KICK_GYRO_THRESHOLD: 150,
  KNEE_ACCEL_THRESHOLD: 15,
  SPRAWL_ACCEL_THRESHOLD: -15,
  
  // Reflex Ridge (Pocket)
  JUMP_ACCEL_THRESHOLD: 12,
  DUCK_ACCEL_THRESHOLD: -8,
  DODGE_ACCEL_THRESHOLD: 8,
  
  // Iron Pump (Hand)
  CURL_ARC_THRESHOLD: 6,
  PRESS_ARC_THRESHOLD: 10,

  // Cardio Core (Pocket/Hand)
  SQUAT_ACCEL_THRESHOLD: 10,
  PUSHUP_ACCEL_THRESHOLD: 8,
  RUN_ACCEL_THRESHOLD: 15,
  BURPEE_ACCEL_THRESHOLD: 20,

  // Warmup Core (Hand)
  ARM_ROTATION_GYRO_THRESHOLD: 200,
  WRIST_ROTATION_GYRO_THRESHOLD: 150,
};

export type GameConfig = typeof DEFAULT_CONFIG;
